name: ✨ Feature Request
description: Suggest an idea or functional enhancement for this project.
title: '[FEAT]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make this project better? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: A clear and concise description of what the problem or limitation is.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the ideal behavior or feature you would like added.
      placeholder: Add a button or setting that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any workaround or alternative solutions you've considered.
      placeholder: Alternatively, we could...
    validations:
      required: false

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a Pull Request for this feature.